spring:
  application:
    name: micr-web
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379

server:
  port: 8000
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# dubbo
dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.youngfinance.front
  consumer:
    check: false
    timeout: 50000
    retries: 0

jwt:
  secret: fa8b00d4c8964aa29b427a8109bb9a35

